### ISSUE TITLE
OrderList 的问题

### ISSUE THREAD

**Issue by yhyyyy1** [AlanZeng423/SoftwarePractice#13]
1. 底部有遮挡如图所示
![微信图片_20230901182921](https://github.com/AlanZeng423/SoftwarePractice/assets/128474470/4a6af3ae-d769-4d35-a8b3-6a50eb8ecba0)
2. 建议在未支付的位置 点击去支付进入Orders页面（因为积分的问题，所以不能进入Payment）

**Comment by yhyyyy1** [comment]
@AlanZeng423

**Comment by yhyyyy1** [comment]
OrderList 未支付 直接去支付已经完成

**Comment by alanzeng423** [comment]
GREAT！
