### ISSUE TITLE
推荐商家实现

### ISSUE THREAD

**Issue by yhyyyy1** [AlanZeng423/SoftwarePractice#19]

**Comment by alanzeng423** [comment]
这么cool

**Comment by yhyyyy1** [comment]
![image](https://github.com/AlanZeng423/SoftwarePractice/assets/128474470/0f835043-4ccf-4a2b-89a9-4ed3dc3b5d36)
Index页面此处的代码一定要改（因该可以借鉴BusinessList）
![image](https://github.com/AlanZeng423/SoftwarePractice/assets/128474470/9d932e3a-87c5-407b-b809-d8465e687564)

**Comment by yhyyyy1** [comment]
> 这么cool
当然没有啦

**Comment by yhyyyy1** [comment]
已经实现
