### ISSUE TITLE
Project.3 Problem

### ISSUE THREAD

**Issue by yhyyyy1** [AlanZeng423/SoftwarePractice#5]
1. Payment页面，无法切换支付方式
2. 缺少支付成功页面，无法进行支付成功后的积分更新
3. 缺少用户页面（对应底部导航栏的“我的”）
4. 主页中的商家点不开

**Comment by alanzeng423** [comment]
1,3已解决

**Comment by yhyyyy1** [comment]
2 4 已经被分出去称为新问题
