### ISSUE TITLE
无法实现支付成功&支付成功累加积分

### ISSUE THREAD

**Issue by alanzeng423** [AlanZeng423/SoftwarePractice#8]

**Comment by yhyyyy1** [comment]
后端已经实现了
按照后端MVC的实现逻辑，分别在Controller层 Service层 Dao层的User文件中有对应的函数——updatePoint
等待前端完成后，开始debug

**Comment by yhyyyy1** [comment]
前后端均已实现，但是发现新问题：
由于前端数据获取不及时，积分虽然在数据库中已经变过了，但是当用户再次下单时，前端保存的积分没有更新，导致积分变更混乱

**Comment by alanzeng423** [comment]
**把前端获取积分从直接读取登录时暂存的数据改为每次都向后端发送请求即可**

**Comment by yhyyyy1** [comment]
OK finish in P3
